anitab-org/portal

systers_portal/static/css/style.css
systers_portal/templates/account/account_inactive.html

Inactive style template recommit responding to:  https://github.com/systers/portal/pull/85

Inactive style template recommit

---

systers_portal/meetup/admin.py
systers_portal/meetup/migrations/0002_meetup.py
systers_portal/meetup/models.py
systers_portal/meetup/tests/test_models.py

Meetup models

---

systers_portal/meetup/mixins.py
systers_portal/meetup/tests/test_mixins.py
systers_portal/meetup/tests/test_views.py
systers_portal/meetup/views.py
systers_portal/templates/meetup/about.html
systers_portal/templates/meetup/base.html
systers_portal/templates/meetup/snippets/about_button.html

Modified base template to show Meetup Location name in all further child templates.

Meetup Base Template

---

systers_portal/meetup/tests/test_views.py
systers_portal/meetup/urls.py
systers_portal/meetup/views.py
systers_portal/static/css/style.css
systers_portal/templates/meetup/list_location.html
systers_portal/templates/meetup/snippets/meetup_locations_grid.html
systers_portal/templates/meetup/snippets/meetup_locations_map.html

I created a separate meetup_locations_map.html snippet for map and included in list_locations.html template even though snippet contain most of js code because I could not find any other optimal option to use Django template tags to use with js.

Listing all meetup locations and map.

---

systers_portal/meetup/tests/test_views.py
systers_portal/meetup/urls.py
systers_portal/meetup/views.py
systers_portal/static/css/style.css
systers_portal/templates/meetup/meetup.html

To see meetup, its title, description, date, time, venue and discussion area.
In style.css I changed `Meetup Location CSS` heading to `Meetup CSS` as now those box CSS are used in meetup page also.

Meetup Page

---

systers_portal/templates/meetup/meetup.html

timeformat for add meetup changed

---

requirements/prod.txt
systers_portal/users/migrations/0003_auto_20160207_1550.py
systers_portal/users/models.py

Kindly review this PR and let me know if  anything needs to be fixed/changed.

Removed django-countries and used django_cities_light for Users.

---

README.md

Additional instructions for solving errors encountered due to a proxy.
Adds to #156

Included instructions in README for working behind proxy

---

README.md

Changes proposed after running into errors with no prior packages installed
Closes #156 
Please review and suggest changes.

Modification in README

---

systers_portal/meetup/migrations/0004_auto_20160307_0457.py
systers_portal/meetup/models.py

Hello,
I checked the develop branch to see whether this issue was already fixed by peer member and found out it hasn't. So have worked on it.
Please review the code for Issue #142
Thanks :)
edit(-Tapasweni):
fixes #142

Issue #142: Venue should be char field

---

systers_portal/templates/base.html

Removed the unnecessary divider in the community dropdown list

---

systers_portal/templates/base.html

Fixed wiki link

---

systers_portal/templates/account/password_reset.html

This is in reference to the issue #209 . Kindly review.

Link contact page on /accounts/password/reset/

---

systers_portal/static/css/style.css
systers_portal/templates/common/contact.html
systers_portal/templates/socialaccount/snippets/provider_list.html

Enhancement of the fix for issue #161.
Added colors to the social-network buttons both on login page and contact page.

Colors added to social buttons

---

systers_portal/static/css/style.css
systers_portal/templates/account/email.html

email style template added

---

systers_portal/templates/community/snippets/community_sidebar.html
systers_portal/templates/community/view_profile.html

When going to view community profile, there is no easy way to get back to community landing page so this PR addresses this problem.

added community landing page link to community sidebar

---

systers_portal/templates/403.html
systers_portal/templates/500.html

Fixes #223 . Please let me know if there is any further customization/designing required as far as the HTML templates are concerned.

Fix #223 Custom 404, 403, 500 error pages

---

README.md

I forgot to mention the proper directory for manage.py in the previous pull request. Apologies!
Please merge this one to correct that.

manage.py directory fix

---

systers_portal/templates/account/password_change.html

This is in reference to #209. Kindly review it once.

Fixes #209 Links contact page on /accounts/password/change

---

systers_portal/users/adapter.py

[#234](https://github.com/systers/portal/issues/234/)

Password validation

---

systers_portal/users/adapter.py

Improved user experience for password validation #247

Modified password validation

---

systers_portal/templates/403.html
systers_portal/templates/404.html
systers_portal/templates/500.html

Used bootstrap and jQuery to hack up a tooltip obtaining referrer page
from document.referrer browser property.
Works on intra site referring. Impossible to implement for an external
referrer outside systers-portal due to browser security settings.
Solves #233.

403,404 and 500 Custom Pages added with tooltip

---

systers_portal/meetup/forms.py
systers_portal/meetup/tests/test_forms.py
systers_portal/meetup/tests/test_views.py
systers_portal/meetup/urls.py
systers_portal/meetup/views.py
systers_portal/templates/meetup/add_meetup_location.html
systers_portal/templates/meetup/edit_meetup_location.html
systers_portal/templates/meetup/meetup_location_confirm_delete.html
systers_portal/templates/meetup/snippets/meetup_location_sidebar.html

Made changes to allow adding, editing and deleting meetup locations

add, edit and delete meetup locations

---

systers_portal/meetup/migrations/0005_meetuplocation_join_requests.py
systers_portal/meetup/migrations/0006_merge.py
systers_portal/meetup/models.py
systers_portal/meetup/tests/test_views.py
systers_portal/meetup/urls.py
systers_portal/meetup/views.py
systers_portal/templates/meetup/join_requests.html
systers_portal/templates/meetup/snippets/join_button.html
systers_portal/templates/meetup/snippets/meetup_location_sidebar.html

Implemented join requests and added tests

meetup - gsoc'16 work

---

systers_portal/blog/views.py
systers_portal/meetup/views.py
systers_portal/templates/blog/post.html
systers_portal/templates/meetup/meetup.html
systers_portal/templates/meetup/snippets/share_buttons.html

Adding Share buttons to a meetup. #268

Share buttons for a meetup

---

systers_portal/templates/base.html

Highlight current route in navbar and nav dropdown
See this in action:
Fixes #196 
- Code

Highlight current route in navbar and nav dropdown

---

systers_portal/templates/base.html
systers_portal/templates/meetup/snippets/meetup_location_sidebar.html

This PR fixes #270
Adding meetup location is changed to the main meetups page.
- Code

Changing add meetup location to Meetups page

---

systers_portal/templates/meetup/base.html

This PR fixes #289 
In communities
In meetups
- Code

Style meetups tabs like in communities

---

systers_portal/community/forms.py
systers_portal/community/permissions.py
systers_portal/community/tests/test_context_processors.py
systers_portal/community/tests/test_forms.py
systers_portal/community/tests/test_permissions.py
systers_portal/community/tests/test_views.py
systers_portal/community/urls.py
systers_portal/community/views.py
systers_portal/templates/base.html
systers_portal/templates/community/add_community.html

This solves issue #267. 
In this PR, Admin would be able to add a new community. To test this, login with your admin credentials.

Add new community by admin

---

README.md

The Readme is updated to include python versions - 3.5 and 3.6
Fixes #308 
- Documentation

Updating readme after migration

---

systers_portal/common/tests/test_views.py
systers_portal/common/views.py
systers_portal/systers_portal/urls.py
systers_portal/templates/base.html

Django allauth built in Logout View has been extended into a custom logout view and cache control decorator has been added.
Fixes #331 
- Code

Fix User Re-Login on a back button

---

systers_portal/systers_portal/settings/base.py
systers_portal/users/forms.py

To esolve the issue ChangePasswordForm was redifined, namely clean_password1() method added.
Fixes #231.

Add 'New password must differ from the old one' check

---

README.md
docs/develop/prerequisites.rst

Signed-off-by: Fenn-25 <fenn25.fn@gmail.com>
Included instructions for portal setup in windows environment in README.md and prerequisites.rst
Fixes #362 
**Developer documentation improvement**
- Documentation
additions to do not affect code, however the additions has passed code coverage tests and all Travis CI tests.

added set up instructions for windows enviroment

---

systers_portal/templates/base.html

Signed-off-by: Fenn-25 <fenn25.fn@gmail.com>
Added request meetup location and view meetup location requests (for staff) in meetup dropdown
Fixes #366 
- Code
- New feature (non-breaking change which adds functionality pre-approved by mentors)
All test passed locally.

added request meetup location to meetup dropdown

---

systers_portal/static/css/bootstrap.min.css
systers_portal/static/css/style.css
systers_portal/templates/community/request_community.html

upgraded UI of request community form as per the branding
Fixes #386 
Before upgradation it looked like:
After upgradation it looks like:
- Code

uprading UI of request_community_form

---

systers_portal/static/css/bootstrap.min.css
systers_portal/static/css/style.css
systers_portal/templates/common/contact.html

upgraded the UI of contact page as per branding guidelines
Fixes #404 
Before:
After:
- Code
- New feature (non-breaking change which adds functionality pre-approved by mentors)

UI upgrade of contact page

---

.codacy.yml

Signed-off-by: Fenn-25 <fenn25.fn@gmail.com>
Add codacy configuration to permit developers exclude certain directories and add custom extensions.
Fixes #394 
Non affective change, tests pass

added empty configuration file codacy

---

systers_portal/templates/common/contact.html

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes #391 
- Code
This has been tested. There exists a [facebook page](https://www.facebook.com/AnitaB.0rg/) that has been linked now.

Update facebook link in contact page

---

systers_portal/static/css/style.css
systers_portal/static/js/choose_profile_pic.js
systers_portal/templates/base.html

Changed css of browse button to match the general style of the form buttons like the cancel button.
Fixes #210 
Before :
After :

Changed css of browse button to match the general style of the form

---

requirements/dev.txt
systers_portal/meetup/tests/test_views.py
systers_portal/meetup/urls.py
systers_portal/meetup/views.py
systers_portal/systers_portal/settings/base.py

Created an API to send meetup data  like event name, venue and start date to VMS. Also, added tests for the same to increase coverage.
Fixes #411 
- Code
- New feature (non-breaking change which adds functionality pre-approved by mentors)
Drafted the Test Cases for both the get and post views created for the API.

API to communicate with VMS

---

systers_portal/community/tests/test_forms.py
systers_portal/meetup/tests/test_views.py

Removes the testing error in meetup/views.py also to maintain coverage test added to community/forms.py.
Fixes #450
- Code

Fixes #450 Removed testing error

---

.travis.yml

Added postgres as a service and made changes in one of the test cases
Fixes #487  
- Code
Ran the Travis CI build successfully on the forked repo and ran all local tests successfully.

Added postgres as a service and modified test

---

systers_portal/meetup/tests/test_views.py

Change a test case which caused the build to fail.
Fixes #502 
- Code
Tested Locally on my system and also travis CI build check.

Modified post_test_view scripts and fixed travis CI build.

---

.gitignore

Add `.vscode/` to `.gitignore`
Fixes #497 
No tests needed.

Update .gitignore to include .vscode/

---

README.md

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
Fixes #399 
- Code
- Documentation
- This change requires a documentation update (software upgrade on readme file)
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

Corrected links in README.md

---

systers_portal/static/css/style.css

Overlapping of messages with Heading/Text is fixed via changes in styling. 
Fixes #460 
- Code
Tested Locally

Changes css, fix overlapping issue

---

systers_portal/templates/account/login.html

Sign Up replaced by Sign In at login page.
Fixes #510 
i have tested it locally.

Sign Up replaced by Sign In at login page

---

README.md

Adding instructions in the README for GDAL installation in Windows.
Fixes #511 
- Documentation

Updating README for setup in Windows

---

systers_portal/static/css/style.css
systers_portal/templates/base.html

Earlier the portal lacked a responsive design and had a lot of glitches at different screen sizes including improper orientation of navbar items at different screen sizes, overlapping of sign in and sign up buttons with the Systers logo on reducing screen sizes and horizontal scrolling on handheld screens. These are resolved as illustrated below in the mocks.
Fixes #458 
- CONTACT orientation fixed.
- Current
- Proposed
- SIGN UP and LOGIN does not overlap Systers Logo on reducing screen width.
- Current
- Proposed
- Orientation of SIGN UP and LOGIN is fixed at reduced screen width.
- Current
- Proposed
- No Horizontal exploring for screens on handheld devices.
- Current
- Proposed
- Other changes include replacement of current sign in and sign up buttons by buttons with rounded edges to …

Remove frontend glitches, Improve responsive css

---

README.md

Added a link that leads to the portal stream on the anita borg zulip organization.
Fixes #482

Added the portal stream link to the readme

---

systers_portal/meetup/views.py

Fixed the RSVP issue which failed while updating the RSVP for more than once
Fixes #311 
- Code
Tested Locally and all tests have passed including the CI build.

Fixed RSVP Update Issue

---

systers_portal/static/css/style.css
systers_portal/templates/base.html

Added 16px margin to right and left of every page as the previous pages were were not having margins.
Fixes #530 
- Code
- 16 px margin added 
- [*] My PR follows the style guidelines of this project
- [*] I have performed a self-review of my own code or materials
- [*] Any dependent changes have been merged 
- [*] My changes generate no new warnings 
- [*] New and existing unit tests pass locally with my changes

left and right margins added to pages

---

systers_portal/static/js/select.js
systers_portal/templates/base.html

Make location selection more user friendly.
Fixes #531
- Code
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
Before changes
After changes

fix: make location selection more user friendly
